sbatch CH_bcc-csm1-1-m.sh
sbatch CH_bcc-csm1-1.sh
sbatch CH_BNU-ESM.sh
sbatch CH_CanESM2.sh
sbatch CH_CCSM4.sh
sbatch CH_CNRM-CM5.sh
sbatch CH_CSIRO-Mk3-6-0.sh
sbatch CH_GFDL-ESM2G.sh
sbatch CH_GFDL-ESM2M.sh
sbatch CH_HadGEM2-CC365.sh
sbatch CH_HadGEM2-ES365.sh
sbatch CH_inmcm4_rcp85.sh
sbatch CH_IPSL-CM5A-LR.sh
sbatch CH_IPSL-CM5A-MR.sh
sbatch CH_IPSL-CM5B-LR.sh
sbatch CH_MIROC5.sh
sbatch CH_MIROC-ESM-CHEM.sh
sbatch CH_MRI-CGCM3.sh
sbatch CH_NorESM1-M.sh
